"""Numerical tools for the ACI major-revision experiments."""

from .channels import (
    CONTINUOUS_FAMILIES,
    DISCRETE_FAMILIES,
    SUPPORTED_FAMILIES,
    ContinuousPosteriorChannel,
    DiscretePosteriorChannel,
    calibrate_epsilon_for_auc,
    calibrate_epsilon_for_information,
    calibrate_logistic_intercept,
    calibrated_discrete_logistic_channel,
    make_continuous_channel,
    make_continuous_channel_for_auc,
    make_continuous_channel_for_information,
    make_channel_for_auc,
    make_channel_for_information,
    make_score_channel,
    rare_spike_channel,
    three_point_channel,
    two_point_frontier_channel,
)
from .information import (
    binary_kl_bits,
    entropy_bits,
    h2,
    mutual_information_from_joint,
    posterior_mutual_information_bits,
)
from .reproducibility import (
    canonical_configuration,
    derive_task_seed,
    make_rng,
    stable_task_seed,
    task_reproducibility_fields,
    task_rng,
    task_seed,
)


__all__ = [
    "h2",
    "binary_kl_bits",
    "entropy_bits",
    "mutual_information_from_joint",
    "posterior_mutual_information_bits",
    "CONTINUOUS_FAMILIES",
    "DISCRETE_FAMILIES",
    "SUPPORTED_FAMILIES",
    "ContinuousPosteriorChannel",
    "DiscretePosteriorChannel",
    "calibrate_logistic_intercept",
    "make_continuous_channel",
    "calibrated_discrete_logistic_channel",
    "rare_spike_channel",
    "three_point_channel",
    "two_point_frontier_channel",
    "make_score_channel",
    "calibrate_epsilon_for_information",
    "calibrate_epsilon_for_auc",
    "make_continuous_channel_for_information",
    "make_continuous_channel_for_auc",
    "make_channel_for_information",
    "make_channel_for_auc",
    "canonical_configuration",
    "stable_task_seed",
    "derive_task_seed",
    "task_seed",
    "make_rng",
    "task_rng",
    "task_reproducibility_fields",
]
